import{S as p,a as m,i as u}from"./assets/vendor-CucEYOFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();document.querySelector("loadMoreButton");const g=new p("ul.gallery a.a-item",{nav:!0,captions:!0,captionsData:"alt",captionsPosition:"bottom",captionType:"attr",sourceAttr:"href",overlay:!0,captionSelector:"img",captionDelay:250}),i=document.querySelector("ul.gallery");function y(e){const r=e.map(o=>`<li class="item-gallery">
                <a href="${o.largeImageURL}" class="a-item">
                  <img
                    class="img-gallery"
                    src="${o.webformatURL}" data-likes='${o.likes}' data-view='${o.views}' data-comments='${o.comments}' data-downloads='${o.downloads}' data-source="${o.largeImageURL}" alt="${o.tags}"
                  />
                </a>
                <ul class='info'>
                  <li>Likes <span class='info-span'>${o.likes}</span></li>
                  <li>Views <span class="info-span">${o.views}</span></li>
                  <li>Comments <span class="info-span">${o.comments}</span></li>
                  <li>Downloads <span class="info-span">${o.downloads}</span></li>
                </ul>
              </li>`);if(i.insertAdjacentHTML("beforeend",r.join("")),g.refresh(),l>1){const s=i.children[(x/15-1)*15+1].getBoundingClientRect().top;window.scrollBy(s)}}function h(){i&&(i.innerHTML="")}function L(){const e=document.querySelector("span.loader");e?e&&e.classList.add("showLoader"):document.querySelector("form").insertAdjacentHTML("afterend","<span class='loader showLoader'></span>")}function f(){const e=document.querySelector("span.loader");e!=!1&&e.classList.contains("showLoader")&&e.classList.remove("showLoader")}function w(){const e=document.querySelector("loadMoreButton");e!=!1&&!e.classList.contains("showLoadMoreButton")&&e.classList.add("showLoadMoreButton")}function b(){const e=document.querySelector("loadMoreButton");e!=!1&&e.classList.contains("showLoadMoreButton")&&e.classList.remove("showLoadMoreButton")}let l=1,d=null;async function v(e,r){const o=await m({method:"get",url:"https://pixabay.com/api/",params:{key:"53619914-87b740f2b3a0dec47a2b3fec9",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,lang:"ua",page:l,per_page:15}});return d=o.data.totalHits,o.data.hits}function M(e){l=e}const n=document.querySelector('input[name="search-text"]'),S=document.querySelector("form");S.addEventListener("submit",e=>{e.preventDefault(),h(),f(),M(1),!(n.value==!1||n.value.trim()=="")&&n.value!==!1&&(L(),v(n.value.trim().toLowerCase()).then(r=>{try{r.length===0?u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:" #ef4040;"}):(w(),y(r))}catch(o){return console.log(o),u.error({message:`Sorry, here ${o}!`,position:"topRight",backgroundColor:" #ef4040;"})}}).finally(()=>{f()}))});d.addEventListener("change",()=>{if(l>d/15)return b(),u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:" #ef4040;"})});
//# sourceMappingURL=index.js.map
