import{S as y,a as L,i as u}from"./assets/vendor-CucEYOFD.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();document.querySelector(".loadMoreButton");const w=new y("ul.gallery a.a-item",{nav:!0,captions:!0,captionsData:"alt",captionsPosition:"bottom",captionType:"attr",sourceAttr:"href",overlay:!0,captionSelector:"img",captionDelay:250}),n=document.querySelector("ul.gallery");function p(e){const a=e.map(o=>`<li class="item-gallery">
                <a href="${o.largeImageURL}" class="a-item">
                  <img
                    class="img-gallery"
                    src="${o.webformatURL}" data-likes='${o.likes}' data-view='${o.views}' data-comments='${o.comments}' data-downloads='${o.downloads}' data-source="${o.largeImageURL}" alt="${o.tags}"
                  />
                </a>
                <ul class='info'>
                  <li>Likes <span class='info-span'>${o.likes}</span></li>
                  <li>Views <span class="info-span">${o.views}</span></li>
                  <li>Comments <span class="info-span">${o.comments}</span></li>
                  <li>Downloads <span class="info-span">${o.downloads}</span></li>
                </ul>
              </li>`);if(n.insertAdjacentHTML("beforeend",a.join("")),w.refresh(),i>1){const l=n.children[(n.children.length/15-1)*15+1].getBoundingClientRect().top;window.scrollBy({top:l,behavior:"smooth"})}}function b(){n&&(n.innerHTML="")}function v(){const e=document.querySelector("span.loader");e?e&&e.classList.add("showLoader"):document.querySelector("form").insertAdjacentHTML("afterend","<span class='loader showLoader'></span>")}function f(){const e=document.querySelector("span.loader");e!=!1&&e.classList.contains("showLoader")&&e.classList.remove("showLoader")}function m(){const e=document.querySelector(".loadMoreButton");e!=!1&&!e.classList.contains("showLoadMoreButton")&&e.classList.add("showLoadMoreButton")}function d(){const e=document.querySelector(".loadMoreButton");e!=!1&&e.classList.contains("showLoadMoreButton")&&e.classList.remove("showLoadMoreButton")}let i=1;async function h(e,a){return(await L({method:"get",url:"https://pixabay.com/api/",params:{key:"53619914-87b740f2b3a0dec47a2b3fec9",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,lang:"ua",page:i,per_page:15}})).data}function g(e){i=e}const s=document.querySelector('input[name="search-text"]'),M=document.querySelector("form"),S=document.querySelector(".loadMoreButton");M.addEventListener("submit",e=>{e.preventDefault(),b(),f(),g(1),!(s.value==!1||s.value.trim()=="")&&s.value!==!1&&(v(),d(),h(s.value.trim().toLowerCase()).then(a=>{try{a.hits.length===0?u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:" #ef4040;"}):(m(),p(a.hits))}catch(o){return u.error({message:`Sorry, here ${o}!`,position:"topRight",backgroundColor:" #ef4040;"})}}).finally(()=>{f()}))});S.addEventListener("click",()=>{d(),g(i+1),h(s.value.trim().toLowerCase()).then(e=>(p(e.hits),m(),e)).then(e=>{i>Math.round(e.totalHits/15)&&(d(),u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"к#6c8cff;"}))})});s.addEventListener("input",()=>{s.style.borderColor="#4e75ff"});
//# sourceMappingURL=index.js.map
