import{a as w,S as b,i}from"./assets/vendor-CucEYOFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))d(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const f of a.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&d(f)}).observe(document,{childList:!0,subtree:!0});function e(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function d(o){if(o.ep)return;o.ep=!0;const a=e(o);fetch(o.href,a)}})();let s=0,l=15;async function h(t,r){const e=await w({method:"get",url:"https://pixabay.com/api/",params:{key:"53619914-87b740f2b3a0dec47a2b3fec9",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,lang:"ua",page:r,per_page:l}});return s=r,e.data}function M(t){s=t}document.querySelector(".loadMoreButton");const v=new b("ul.gallery a.a-item",{nav:!0,captions:!0,captionsData:"alt",captionsPosition:"bottom",captionType:"attr",sourceAttr:"href",overlay:!0,captionSelector:"img",captionDelay:250}),p=document.querySelector("ul.gallery");function m(t){const r=t.map(e=>`<li class="item-gallery">
                <a href="${e.largeImageURL}" class="a-item">
                  <img
                    class="img-gallery"
                    src="${e.webformatURL}" data-likes='${e.likes}' data-view='${e.views}' data-comments='${e.comments}' data-downloads='${e.downloads}' data-source="${e.largeImageURL}" alt="${e.tags}"
                  />
                </a>
                <ul class='info'>
                  <li>Likes <span class='info-span'>${e.likes}</span></li>
                  <li>Views <span class="info-span">${e.views}</span></li>
                  <li>Comments <span class="info-span">${e.comments}</span></li>
                  <li>Downloads <span class="info-span">${e.downloads}</span></li>
                </ul>
              </li>`);p.insertAdjacentHTML("beforeend",r.join("")),v.refresh()}function S(){p&&(p.innerHTML="")}function g(){const t=document.querySelector("span.loader");t?t&&t.classList.add("showLoader"):document.querySelector("form").insertAdjacentHTML("afterend","<span class='loader showLoader'></span>")}function u(){const t=document.querySelector("span.loader");t&&t.classList.contains("showLoader")&&t.classList.remove("showLoader")}function y(){const t=document.querySelector(".loadMoreButton");t&&!t.classList.contains("showLoadMoreButton")&&t.classList.add("showLoadMoreButton")}function c(){const t=document.querySelector(".loadMoreButton");t&&t.classList.contains("showLoadMoreButton")&&t.classList.remove("showLoadMoreButton")}const n=document.querySelector('input[name="search-text"]'),q=document.querySelector("form"),B=document.querySelector(".loadMoreButton");let L=null;q.addEventListener("submit",t=>{t.preventDefault();async function r(){if(S(),u(),n.value.trim()!=""&&n.value!==!1){g(),c();try{const e=await h(n.value.trim().toLowerCase(),35);L=e,e.hits.length===0&&e.totalHits===0?i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:" #ef4040;"}):s>Math.ceil(e.totalHits/l)?(c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#6c8cff;"}),e.totalHits<=l&&m(e.hits)):(y(),m(e.hits))}catch(e){i.error({message:`Sorry, here ${e}!`,position:"topRight",backgroundColor:" #ef4040;"})}u()}}r()});B.addEventListener("click",()=>{async function t(){try{if(g(),c(),M(s+1),s>Math.ceil(L.totalHits/l))c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#6c8cff;"});else{const r=await h(n.value.trim().toLowerCase(),s);if(m(r.hits),s>1){let o=document.querySelector("li.item-gallery").getBoundingClientRect().height*2;window.scrollBy({top:o,behavior:"smooth"}),y()}u(),c()}}catch(r){i.error({message:`Sorry, here ${r}!`,position:"topRight",backgroundColor:" #ef4040;"})}u()}t()});n.addEventListener("input",()=>{n.style.borderColor="#4e75ff"});
//# sourceMappingURL=index.js.map
